[project]
name = "lowlevel-mcp"
version = "0.1.0"
description = "Example MCP server providing some low-level server information"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=3.0.0b2",
]
