apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- daemonset.yaml

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: lowlevel-mcp

# Images set at deploy time
images:
- name: quay.io/REPLACE_WITH_YOUR_USERNAME/lowlevel-mcp
  newName: quay.io/javierpena/lowlevel-mcp
  newTag: latest
